### ISSUE TITLE
Exposing name_format to config

### ISSUE THREAD

**Issue by papakay** [handnot2/samly#23]
@handnot2 please can you kindly update the name_format in the function below to use the nameid_format property provided in the idp configuration?

helper.ex

```
def gen_idp_signin_req(sp, idp_metadata) do
    idp_signin_url = Esaml.esaml_idp_metadata(idp_metadata, :login_location)
    # TODO: Expose an config
    name_format = 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient'
    xml_frag = :esaml_sp.generate_authn_request(idp_signin_url, sp, name_format)
    {idp_signin_url, xml_frag}
  end
```

**Comment by papakay** [comment]
I'm using this `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`.

**Comment by handnot2** [comment]
Can you checkout [nameid_format_from_metadata](https://github.com/handnot2/samly/tree/nameid_format_from_metadata) branch and verify the fix?
