### ISSUE TITLE
Mixed case in response headers

### ISSUE THREAD

**Issue by meadoch1** [handnot2/samly#39]
Thank you for the good library for SAML.  While incorporating it I found that, although the Plug.Conn docs suggest that all response header keys be entered in lower case (ref: https://hexdocs.pm/plug/Plug.Conn.html#put_resp_header/3) and that an error will be thrown in tests if mixed case values are included, there are instances of calls to `Plug.Conn.put_resp_header/3` which use mixed case and will fail in controller tests using helper functions like `get` and `post`.  

If you are open to a PR against this I'll be glad to offer one addressing this.

**Comment by handnot2** [comment]
PR would be great. Thanks.
