### ISSUE TITLE
add idp_id to Assertion prior to piping through pre_session_create_pipeline

### ISSUE THREAD

**Issue by jgautsch** [handnot2/samly#45]
I have a use-case where I'd like to access `assertion.idp_id` inside my `pre_session_create_pipeline` plug. 

Presently `idp_id` is set on the assertion _after_ the `pre_session_create_pipeline` plug is executed, so the plug sees `%Assertion{idp_id: nil}`. [Here is the relevant code.](https://github.com/handnot2/samly/blob/032281091ea933b925f86b537cacfbaa791bacc3/lib/samly/sp_handler.ex#L43)

I suggest that `idp_id` be set on the `Assertion` struct prior to it being passed to the `pre_session_create_pipeline`.

Another way for me to accomplish this without code changes is to access `conn.private[:samly_idp]`, which works fine, although the suggested change feels like a cleaner division between application code and library implementation details.

Thanks for a great package. I'm happy to submit a PR for this.

**Comment by handnot2** [comment]
Thanks for the suggestion. It was a simple fix. Will roll this into a hex release along with a few other items.
