### ISSUE TITLE
0.8.2 not matching SP metadata set in Shibboleth

### ISSUE THREAD

**Issue by nwallis** [handnot2/samly#8]
After configuring Shibboleth correctly to work with my application which is an SP and using 0.8.1, I was able to see the Shibboleth login screen. 

However after using 0.8.2 with the same working Shibboleth configuration, my SP was no longer recognised by Shibboleth.  It appears to be a difference between the two AuthnRequest being sent from the SP.  I have attached both for you to take a look at.

[xml.zip](https://github.com/handnot2/samly/files/1480441/xml.zip)

**Comment by handnot2** [comment]
Fix is available in `sp_entity_id_not_set` branch. Please confirm if it addresses the issue.

**Comment by nwallis** [comment]
Yep, its all working now... thanks.
